export type NavItem = { id: string; title: string };
export type NavSection = { id: string; title: string; children?: NavItem[] };

export const navigationSectionsUk: NavSection[] = [
  { id: 'introduction', title: 'Все про фріланс в Польщі станом на 2026', children: [
    { id: 'introduction-1', title: 'Чому Польща стала хабом для українських фрілансерів?' },
    { id: 'introduction-2', title: 'Статистика фрілансу в Польщі' },
    { id: 'introduction-3', title: 'Найзатребуваніші професії та середні заробітні плати' },
    { id: 'introduction-4', title: 'Платформи для фрілансерів' },
    { id: 'introduction-5', title: 'Середні погодинні ставки' },
  ]},
  { id: 'legal-status', title: 'Легальне перебування і фріланс в Польщі', children: [
    { id: 'legal-status-1', title: 'Статус PESEL UKR та його актуальність у 2026 році' },
    { id: 'legal-status-2', title: 'Право на ведення господарської діяльності для громадян України' },
    { id: 'legal-status-3', title: 'Карта тимчасового побиту на підставі бізнесу' },
    { id: 'legal-status-4', title: 'Blue Card для висококваліфікованих IT-фрілансерів' },
    { id: 'legal-status-5', title: 'Можливість роботи за візою або в рамках безвізового руху' },
  ]},
  { id: 'unregistered-activity', title: 'Незареєстрована діяльність', children: [
    { id: 'unregistered-activity-1', title: 'Що таке незареєстрована діяльність?' },
    { id: 'unregistered-activity-2', title: 'Фінансовий ліміт доходу у 2026 році' },
    { id: 'unregistered-activity-3', title: 'Хто має право на цю форму?' },
    { id: 'unregistered-activity-4', title: "Перелік обов'язків - спрощений реєстр" },
    { id: 'unregistered-activity-5', title: 'Питання страхування (ZUS)' },
    { id: 'unregistered-activity-6', title: 'Податкова звітність (PIT-36)' },
  ]},
  { id: 'jdg', title: 'Jednoosobowa Działalność Gospodarcza (JDG)', children: [
    { id: 'jdg-1', title: 'Покроковий алгоритм реєстрації через CEIDG' },
    { id: 'jdg-2', title: 'Вибір кодів діяльності (PKD)' },
    { id: 'jdg-3', title: 'Вибір дати початку та місце реєстрації' },
    { id: 'jdg-4', title: 'Реєстрація в ZUS - форми ZZA та ZUA' },
    { id: 'jdg-5', title: 'Банківський рахунок - приватний чи фірмовий?' },
    { id: 'jdg-6', title: 'Фінансова та майнова відповідальність' },
  ]},
  { id: 'business-incubators', title: 'Фріланс чи навіть робота через Бізнес-інкубатори', children: [
    { id: 'business-incubators-1', title: 'Принцип роботи моделі "Freelance as a Service"' },
    { id: 'business-incubators-2', title: 'Переваги для іноземців (з обережністю)' },
    { id: 'business-incubators-3', title: 'Аналіз витрат - абонплата проти податків' },
    { id: 'business-incubators-4', title: 'Відповідальність у бізнес-інкубаторах' },
    { id: 'business-incubators-5', title: 'Питання легалізації та Карти побиту' },
    { id: 'business-incubators-6', title: 'Обмеження моделі' },
    { id: 'business-incubators-7', title: 'Переваги для іноземців без знання мови та бухгалтерії' },
    { id: 'business-incubators-8', title: 'Аналіз витрат - щомісячна абонплата проти податків JDG' },
    { id: 'business-incubators-9', title: 'Питання легалізації (карти побиту) через інкубатор' },
    { id: 'business-incubators-10', title: 'Обмеження у видах діяльності в рамках інкубатора' },
  ]},
  { id: 'civil-contracts', title: 'Цивільно-правові договори (B2C)', children: [
    { id: 'civil-contracts-1', title: 'Umowa o dzieło: Специфіка для творчих професій' },
    { id: 'civil-contracts-2', title: 'Umowa zlecenie: Оплата за процес' },
    { id: 'civil-contracts-3', title: 'Порівняння "брутто" та "нетто" для фрілансера' },
    { id: 'civil-contracts-4', title: 'Оподаткування доходів з-за кордону' },
    { id: 'civil-contracts-5', title: 'Umowa zlecenie: правила оподаткування та соціальні внески' },
    { id: 'civil-contracts-6', title: 'Порівняння "брутто" та "нетто" (договори)' },
    { id: 'civil-contracts-7', title: 'Оподаткування доходів з-за кордону через ці договори' },
  ]},
  { id: 'laws-regulations', title: 'Закони, норми та державне регулювання', children: [
    { id: 'laws-regulations-1', title: 'Закон про підприємців (Ustawa o przedsiębiorcach)' },
    { id: 'laws-regulations-2', title: 'Податковий кодекс (Ordynacja podatkowa)' },
    { id: 'laws-regulations-3', title: 'Права фрілансера під час перевірок (KAS)' },
    { id: 'laws-regulations-4', title: 'Захист персональних даних (RODO)' },
    { id: 'laws-regulations-5', title: "Офіційні роз'яснення щодо віддаленої роботи" },
  ]},
  { id: 'taxation-systems', title: 'Глибокий аналіз систем оподаткування', children: [
    { id: 'taxation-systems-1', title: 'Skala podatkowa (Загальна система 12% / 32%)' },
    { id: 'taxation-systems-2', title: 'Podatek liniowy (Лінійний податок 19%)' },
    { id: 'taxation-systems-3', title: 'Ryczałt (Ричалт, податок від обороту)' },
    { id: 'taxation-systems-4', title: 'Ryczałt: детальний розбір ставок' },
    { id: 'taxation-systems-5', title: 'Критерії вибору найвигіднішої системи у 2026 році' },
  ]},
  { id: 'zus-insurance', title: 'Соціальне страхування та ZUS', children: [
    { id: 'zus-insurance-1', title: 'Пільга "Ulga na start"' },
    { id: 'zus-insurance-2', title: 'Mały ZUS Plus' },
    { id: 'zus-insurance-3', title: 'Стандартні внески та "Chorobowe"' },
  ]},
  { id: 'vat', title: 'ПДВ (VAT) у житті фрілансера', children: [
    { id: 'vat-1', title: 'Ліміт 200 000 злотих' },
    { id: 'vat-2', title: 'Реєстрація VAT-UE' },
  ]},
  { id: 'accounting-finance', title: 'Бухгалтерія та фінансова гігієна', children: [
    { id: 'accounting-finance-1', title: 'Ведення KPiR (Книга доходів і витрат)' },
    { id: 'accounting-finance-2', title: 'Система KSeF у 2026 році' },
    { id: 'accounting-finance-3', title: 'Витрати, що зменшують податок' },
    { id: 'accounting-finance-4', title: 'Де шукати бухгалтера?' },
    { id: 'accounting-finance-5', title: 'Електронне фактурування та система KSeF у 2026 році' },
    { id: 'accounting-finance-6', title: 'Витрати, що зменшують податок - оренда, техніка, навчання, авто' },
    { id: 'accounting-finance-7', title: 'Професійна допомога - Biuro rachunkowe проти онлайн-сервісів' },
  ]},
  { id: 'technical-legal', title: 'Додаткові технічні та правові аспекти', children: [
    { id: 'technical-legal-1', title: 'Profil Zaufany та mObywatel' },
    { id: 'technical-legal-2', title: 'Електронний підпис (Podpis kwalifikowany)' },
    { id: 'technical-legal-3', title: 'Робота з іноземними платформами (Upwork, Fiverr)' },
  ]},
  { id: 'conclusions', title: 'Висновки - стратегія успішного фрілансу', children: [
    { id: 'conclusions-1', title: 'Ваш чек-лист на старт' },
    { id: 'conclusions-2', title: 'Стратегія успішного фрілансу' },
  ]},
  { id: 'employment-vs-selfemployed', title: 'Самозайнятість vs Umowa o pracę - що вигідніше?', children: [
    { id: 'employment-vs-selfemployed-1', title: 'Відпустки та лікарняні' },
    { id: 'employment-vs-selfemployed-2', title: 'Стабільність' },
    { id: 'employment-vs-selfemployed-3', title: 'Гроші на руки' },
  ]},
  { id: 'legal-liability', title: 'Юридична відповідальність фрілансера', children: [
    { id: 'legal-liability-1', title: 'Відповідальність усім майном' },
    { id: 'legal-liability-2', title: 'Страхування професійної відповідальності (OC)' },
  ]},
  { id: 'b2b-contracts', title: 'Специфіка B2B-контракту', children: [
    { id: 'b2b-contracts-1', title: 'Ознаки трудових відносин' },
    { id: 'b2b-contracts-2', title: 'Працювати на колишнього роботодавця' },
  ]},
  { id: 'reporting-requirements', title: 'Вимоги до звітності та перевірки', children: [
    { id: 'reporting-requirements-1', title: 'Реєстрація в статистиці (REGON)' },
    { id: 'reporting-requirements-2', title: 'Перевірки ZUS' },
    { id: 'reporting-requirements-3', title: 'Перевірки податкової' },
  ]},
  { id: 'how-to-start', title: 'Як стати фрілансером - поради для початківців', children: [
    { id: 'how-to-start-1', title: 'Як визначити свою професію та напрямок?' },
    { id: 'how-to-start-2', title: 'На кого варто починати? Професії для новачків' },
    { id: 'how-to-start-3', title: 'Куди йти - платформи та способи пошуку клієнтів' },
    { id: 'how-to-start-4', title: 'Навчання - курси та ресурси' },
    { id: 'how-to-start-5', title: 'Мови навчання - таблиця доступності курсів' },
    { id: 'how-to-start-6', title: 'Практичні поради для старту' },
  ]},
  { id: 'faq', title: 'FAQ - Запитання та відповіді', children: [
    { id: 'faq-1', title: 'Основні питання про реєстрацію' },
    { id: 'faq-2', title: 'Питання про оподаткування' },
    { id: 'faq-3', title: 'Питання про ZUS' },
    { id: 'faq-4', title: 'Питання про VAT' },
    { id: 'faq-5', title: 'Питання про бухгалтерію' },
    { id: 'faq-6', title: 'Питання про міжнародні доходи' },
    { id: 'faq-7', title: 'Питання про легалізацію' },
    { id: 'faq-8', title: 'Питання про B2B-контракти та трудові відносини' },
    { id: 'faq-9', title: 'Питання про відповідальність' },
  ]},
];

export const navigationSectionsPl: NavSection[] = [
  { id: 'introduction', title: 'Wszystko o freelancingu w Polsce na 2026', children: [
    { id: 'introduction-1', title: 'Dlaczego Polska stała się hubem dla ukraińskich freelancerów?' },
    { id: 'introduction-2', title: 'Statystyki freelancingu w Polsce' },
    { id: 'introduction-3', title: 'Najbardziej poszukiwane zawody i średnie zarobki' },
    { id: 'introduction-4', title: 'Platformy dla freelancerów' },
    { id: 'introduction-5', title: 'Średnie stawki godzinowe' },
  ]},
  { id: 'legal-status', title: 'Legalny pobyt i freelancing w Polsce', children: [
    { id: 'legal-status-1', title: 'Status PESEL UKR i jego aktualność w 2026' },
    { id: 'legal-status-2', title: 'Prawo do prowadzenia działalności dla obywateli Ukrainy' },
    { id: 'legal-status-3', title: 'Karta czasowego pobytu na podstawie biznesu' },
    { id: 'legal-status-4', title: 'Blue Card dla wysoko wykwalifikowanych IT-freelancerów' },
    { id: 'legal-status-5', title: 'Możliwość pracy na wizę lub w ruchu bezwizowym' },
  ]},
  { id: 'unregistered-activity', title: 'Działalność nierejestrowana', children: [
    { id: 'unregistered-activity-1', title: 'Czym jest działalność nierejestrowana?' },
    { id: 'unregistered-activity-2', title: 'Limit finansowy dochodu w 2026' },
    { id: 'unregistered-activity-3', title: 'Kto ma prawo do tej formy?' },
    { id: 'unregistered-activity-4', title: 'Wykaz obowiązków - uproszczony rejestr' },
    { id: 'unregistered-activity-5', title: 'Kwestie ubezpieczeń (ZUS)' },
    { id: 'unregistered-activity-6', title: 'Sprawozdawczość podatkowa (PIT-36)' },
  ]},
  { id: 'jdg', title: 'Jednoosobowa Działalność Gospodarcza (JDG)', children: [
    { id: 'jdg-1', title: 'Algorytm rejestracji przez CEIDG krok po kroku' },
    { id: 'jdg-2', title: 'Wybór kodów działalności (PKD)' },
    { id: 'jdg-3', title: 'Wybór daty rozpoczęcia i miejsce rejestracji' },
    { id: 'jdg-4', title: 'Rejestracja w ZUS - formularze ZZA i ZUA' },
    { id: 'jdg-5', title: 'Konto bankowe - prywatne czy firmowe?' },
    { id: 'jdg-6', title: 'Odpowiedzialność finansowa i majątkowa' },
  ]},
  { id: 'business-incubators', title: 'Freelancing lub nawet praca przez Inkubatory biznesowe', children: [
    { id: 'business-incubators-1', title: 'Zasada modelu "Freelance as a Service"' },
    { id: 'business-incubators-2', title: 'Korzyści dla cudzoziemców (z ostrożnością)' },
    { id: 'business-incubators-3', title: 'Analiza kosztów - abonament vs podatki' },
    { id: 'business-incubators-4', title: 'Odpowiedzialność w inkubatorach' },
    { id: 'business-incubators-5', title: 'Kwestie legalizacji i Karty pobytu' },
    { id: 'business-incubators-6', title: 'Ograniczenia modelu' },
    { id: 'business-incubators-7', title: 'Korzyści dla cudzoziemców bez znajomości języka i księgowości' },
    { id: 'business-incubators-8', title: 'Analiza kosztów - abonament miesięczny vs podatki JDG' },
    { id: 'business-incubators-9', title: 'Kwestie legalizacji (karty pobytu) przez inkubator' },
    { id: 'business-incubators-10', title: 'Ograniczenia rodzajów działalności w inkubatorze' },
  ]},
  { id: 'civil-contracts', title: 'Umowy cywilnoprawne (B2C)', children: [
    { id: 'civil-contracts-1', title: 'Umowa o dzieło: Specyfika dla zawodów kreatywnych' },
    { id: 'civil-contracts-2', title: 'Umowa zlecenie: Płatność za proces' },
    { id: 'civil-contracts-3', title: 'Porównanie "brutto" i "netto" dla freelancera' },
    { id: 'civil-contracts-4', title: 'Opodatkowanie dochodów z zagranicy' },
    { id: 'civil-contracts-5', title: 'Umowa zlecenie: zasady opodatkowania i składki społeczne' },
    { id: 'civil-contracts-6', title: 'Porównanie "brutto" i "netto" (umowy)' },
    { id: 'civil-contracts-7', title: 'Opodatkowanie dochodów z zagranicy przez te umowy' },
  ]},
  { id: 'laws-regulations', title: 'Prawa, normy i regulacje państwowe', children: [
    { id: 'laws-regulations-1', title: 'Ustawa o przedsiębiorcach' },
    { id: 'laws-regulations-2', title: 'Ordynacja podatkowa' },
    { id: 'laws-regulations-3', title: 'Prawa freelancera podczas kontroli (KAS)' },
    { id: 'laws-regulations-4', title: 'Ochrona danych osobowych (RODO)' },
    { id: 'laws-regulations-5', title: 'Oficjalne wyjaśnienia dotyczące pracy zdalnej' },
  ]},
  { id: 'taxation-systems', title: 'Szczegółowa analiza systemów podatkowych', children: [
    { id: 'taxation-systems-1', title: 'Skala podatkowa (12% / 32%)' },
    { id: 'taxation-systems-2', title: 'Podatek liniowy (19%)' },
    { id: 'taxation-systems-3', title: 'Ryczałt (podatek od obrotu)' },
    { id: 'taxation-systems-4', title: 'Ryczałt: szczegółowe stawki' },
    { id: 'taxation-systems-5', title: 'Kryteria wyboru najkorzystniejszego systemu w 2026' },
  ]},
  { id: 'zus-insurance', title: 'Ubezpieczenia społeczne i ZUS', children: [
    { id: 'zus-insurance-1', title: 'Ulga na start' },
    { id: 'zus-insurance-2', title: 'Mały ZUS Plus' },
    { id: 'zus-insurance-3', title: 'Standardowe składki i "Chorobowe"' },
  ]},
  { id: 'vat', title: 'VAT w życiu freelancera', children: [
    { id: 'vat-1', title: 'Limit 200 000 zł' },
    { id: 'vat-2', title: 'Rejestracja VAT-UE' },
  ]},
  { id: 'accounting-finance', title: 'Księgowość i higiena finansowa', children: [
    { id: 'accounting-finance-1', title: 'Prowadzenie KPiR' },
    { id: 'accounting-finance-2', title: 'System KSeF w 2026' },
    { id: 'accounting-finance-3', title: 'Koszty obniżające podatek' },
    { id: 'accounting-finance-4', title: 'Gdzie szukać księgowego?' },
    { id: 'accounting-finance-5', title: 'Fakturowanie elektroniczne i KSeF w 2026' },
    { id: 'accounting-finance-6', title: 'Koszty obniżające podatek - wynajem, sprzęt, szkolenia, auto' },
    { id: 'accounting-finance-7', title: 'Pomoc profesjonalna - Biuro rachunkowe vs serwisy online' },
  ]},
  { id: 'technical-legal', title: 'Dodatkowe aspekty techniczne i prawne', children: [
    { id: 'technical-legal-1', title: 'Profil Zaufany i mObywatel' },
    { id: 'technical-legal-2', title: 'Podpis kwalifikowany' },
    { id: 'technical-legal-3', title: 'Praca z zagranicznymi platformami (Upwork, Fiverr)' },
  ]},
  { id: 'conclusions', title: 'Wnioski - strategia udanego freelancingu', children: [
    { id: 'conclusions-1', title: 'Twój checklist na start' },
    { id: 'conclusions-2', title: 'Strategia udanego freelancingu' },
  ]},
  { id: 'employment-vs-selfemployed', title: 'Samozatrudnienie vs Umowa o pracę - co jest korzystniejsze?', children: [
    { id: 'employment-vs-selfemployed-1', title: 'Urlopy i zwolnienia lekarskie' },
    { id: 'employment-vs-selfemployed-2', title: 'Stabilność' },
    { id: 'employment-vs-selfemployed-3', title: 'Pieniądze do ręki' },
  ]},
  { id: 'legal-liability', title: 'Odpowiedzialność prawna freelancera', children: [
    { id: 'legal-liability-1', title: 'Odpowiedzialność całym majątkiem' },
    { id: 'legal-liability-2', title: 'Ubezpieczenie OC zawodowe' },
  ]},
  { id: 'b2b-contracts', title: 'Specyfika umowy B2B', children: [
    { id: 'b2b-contracts-1', title: 'Znamiona stosunku pracy' },
    { id: 'b2b-contracts-2', title: 'Praca u byłego pracodawcy' },
  ]},
  { id: 'reporting-requirements', title: 'Wymagania dotyczące sprawozdawczości i kontroli', children: [
    { id: 'reporting-requirements-1', title: 'Rejestracja w statystyce (REGON)' },
    { id: 'reporting-requirements-2', title: 'Kontrole ZUS' },
    { id: 'reporting-requirements-3', title: 'Kontrole podatkowe' },
  ]},
  { id: 'how-to-start', title: 'Jak zostać freelancerem - porady dla początkujących', children: [
    { id: 'how-to-start-1', title: 'Jak określić swój zawód i kierunek?' },
    { id: 'how-to-start-2', title: 'Dla kogo warto zaczynać? Zawody dla początkujących' },
    { id: 'how-to-start-3', title: 'Gdzie szukać - platformy i sposoby znajdowania klientów' },
    { id: 'how-to-start-4', title: 'Szkolenia - kursy i zasoby' },
    { id: 'how-to-start-5', title: 'Języki szkoleń - dostępność kursów' },
    { id: 'how-to-start-6', title: 'Praktyczne porady na start' },
  ]},
  { id: 'faq', title: 'FAQ - Pytania i odpowiedzi', children: [
    { id: 'faq-1', title: 'Podstawowe pytania o rejestrację' },
    { id: 'faq-2', title: 'Pytania o opodatkowanie' },
    { id: 'faq-3', title: 'Pytania o ZUS' },
    { id: 'faq-4', title: 'Pytania o VAT' },
    { id: 'faq-5', title: 'Pytania o księgowość' },
    { id: 'faq-6', title: 'Pytania o dochody międzynarodowe' },
    { id: 'faq-7', title: 'Pytania o legalizację' },
    { id: 'faq-8', title: 'Pytania o umowy B2B i stosunek pracy' },
    { id: 'faq-9', title: 'Pytania o odpowiedzialność' },
  ]},
];

export const navigationSectionsEn: NavSection[] = [
  { id: 'introduction', title: 'All about freelancing in Poland in 2026', children: [
    { id: 'introduction-1', title: 'Why Poland became a hub for international freelancers?' },
    { id: 'introduction-2', title: 'Freelancing statistics in Poland' },
    { id: 'introduction-3', title: 'Most in-demand professions and average rates' },
    { id: 'introduction-4', title: 'Freelance platforms' },
    { id: 'introduction-5', title: 'Average hourly rates' },
  ]},
  { id: 'legal-status', title: 'Legal residence and freelancing in Poland', children: [
    { id: 'legal-status-1', title: 'PESEL and residence status in 2026' },
    { id: 'legal-status-2', title: 'Right to run a business for non-EU citizens' },
    { id: 'legal-status-3', title: 'Temporary residence card on business grounds' },
    { id: 'legal-status-4', title: 'EU Blue Card for highly qualified IT freelancers' },
    { id: 'legal-status-5', title: 'Working on a visa or visa-free' },
  ]},
  { id: 'unregistered-activity', title: 'Unregistered activity', children: [
    { id: 'unregistered-activity-1', title: 'What is unregistered activity?' },
    { id: 'unregistered-activity-2', title: 'Income limit in 2026' },
    { id: 'unregistered-activity-3', title: 'Who is entitled to this form?' },
    { id: 'unregistered-activity-4', title: 'List of obligations - simplified register' },
    { id: 'unregistered-activity-5', title: 'Insurance (ZUS) questions' },
    { id: 'unregistered-activity-6', title: 'Tax reporting (PIT-36)' },
  ]},
  { id: 'jdg', title: 'Jednoosobowa Działalność Gospodarcza (JDG)', children: [
    { id: 'jdg-1', title: 'Step-by-step registration via CEIDG' },
    { id: 'jdg-2', title: 'Choosing activity codes (PKD)' },
    { id: 'jdg-3', title: 'Start date and place of registration' },
    { id: 'jdg-4', title: 'ZUS registration - ZZA and ZUA forms' },
    { id: 'jdg-5', title: 'Bank account - personal or business?' },
    { id: 'jdg-6', title: 'Financial and asset liability' },
  ]},
  { id: 'business-incubators', title: 'Freelancing through business incubators', children: [
    { id: 'business-incubators-1', title: 'How the "Freelance as a Service" model works' },
    { id: 'business-incubators-2', title: 'Benefits for foreigners (with caution)' },
    { id: 'business-incubators-3', title: 'Cost analysis - subscription vs tax' },
    { id: 'business-incubators-4', title: 'Liability in business incubators' },
    { id: 'business-incubators-5', title: 'Residence permit and legalisation' },
    { id: 'business-incubators-6', title: 'Model limitations' },
    { id: 'business-incubators-7', title: 'Benefits for foreigners without language/accounting' },
    { id: 'business-incubators-8', title: 'Cost analysis - monthly fee vs JDG tax' },
    { id: 'business-incubators-9', title: 'Legalisation (residence) via incubator' },
    { id: 'business-incubators-10', title: 'Activity limits in incubators' },
  ]},
  { id: 'civil-contracts', title: 'Civil-law contracts (B2C)', children: [
    { id: 'civil-contracts-1', title: 'Umowa o dzieło: For creative professions' },
    { id: 'civil-contracts-2', title: 'Umowa zlecenie: Payment for process' },
    { id: 'civil-contracts-3', title: 'Gross vs net for the freelancer' },
    { id: 'civil-contracts-4', title: 'Taxation of foreign income' },
    { id: 'civil-contracts-5', title: 'Umowa zlecenie: tax and social contributions' },
    { id: 'civil-contracts-6', title: 'Gross vs net (contracts)' },
    { id: 'civil-contracts-7', title: 'Taxation of foreign income under these contracts' },
  ]},
  { id: 'laws-regulations', title: 'Laws, norms and state regulation', children: [
    { id: 'laws-regulations-1', title: 'Entrepreneurs Act (Ustawa o przedsiębiorcach)' },
    { id: 'laws-regulations-2', title: 'Tax Code (Ordynacja podatkowa)' },
    { id: 'laws-regulations-3', title: 'Freelancer rights during checks (KAS)' },
    { id: 'laws-regulations-4', title: 'Data protection (GDPR)' },
    { id: 'laws-regulations-5', title: 'Official guidance on remote work' },
  ]},
  { id: 'taxation-systems', title: 'Tax systems in depth', children: [
    { id: 'taxation-systems-1', title: 'Tax scale (12% / 32%)' },
    { id: 'taxation-systems-2', title: 'Flat tax (19%)' },
    { id: 'taxation-systems-3', title: 'Lump sum (ryczałt)' },
    { id: 'taxation-systems-4', title: 'Ryczałt: detailed rates' },
    { id: 'taxation-systems-5', title: 'Choosing the best system in 2026' },
  ]},
  { id: 'zus-insurance', title: 'Social insurance and ZUS', children: [
    { id: 'zus-insurance-1', title: '"Ulga na start" relief' },
    { id: 'zus-insurance-2', title: 'Mały ZUS Plus' },
    { id: 'zus-insurance-3', title: 'Standard contributions and "Chorobowe"' },
  ]},
  { id: 'vat', title: 'VAT for freelancers', children: [
    { id: 'vat-1', title: '200,000 PLN limit' },
    { id: 'vat-2', title: 'VAT-EU registration' },
  ]},
  { id: 'accounting-finance', title: 'Accounting and financial hygiene', children: [
    { id: 'accounting-finance-1', title: 'Keeping KPiR (revenue and expense ledger)' },
    { id: 'accounting-finance-2', title: 'KSeF system in 2026' },
    { id: 'accounting-finance-3', title: 'Tax-deductible costs' },
    { id: 'accounting-finance-4', title: 'Where to find an accountant?' },
    { id: 'accounting-finance-5', title: 'E-invoicing and KSeF in 2026' },
    { id: 'accounting-finance-6', title: 'Tax-deductible costs - rent, equipment, training, car' },
    { id: 'accounting-finance-7', title: 'Professional help - office vs online' },
  ]},
  { id: 'technical-legal', title: 'Technical and legal aspects', children: [
    { id: 'technical-legal-1', title: 'Profil Zaufany and mObywatel' },
    { id: 'technical-legal-2', title: 'Qualified e-signature' },
    { id: 'technical-legal-3', title: 'Working with foreign platforms (Upwork, Fiverr)' },
  ]},
  { id: 'conclusions', title: 'Conclusions - successful freelancing strategy', children: [
    { id: 'conclusions-1', title: 'Your start checklist' },
    { id: 'conclusions-2', title: 'Successful freelancing strategy' },
  ]},
  { id: 'employment-vs-selfemployed', title: 'Self-employment vs employment - which is better?', children: [
    { id: 'employment-vs-selfemployed-1', title: 'Holidays and sick leave' },
    { id: 'employment-vs-selfemployed-2', title: 'Stability' },
    { id: 'employment-vs-selfemployed-3', title: 'Take-home pay' },
  ]},
  { id: 'legal-liability', title: 'Legal liability of a freelancer', children: [
    { id: 'legal-liability-1', title: 'Liability with all assets' },
    { id: 'legal-liability-2', title: 'Professional indemnity insurance (OC)' },
  ]},
  { id: 'b2b-contracts', title: 'B2B contract specifics', children: [
    { id: 'b2b-contracts-1', title: 'Signs of employment relationship' },
    { id: 'b2b-contracts-2', title: 'Working for a former employer' },
  ]},
  { id: 'reporting-requirements', title: 'Reporting and inspections', children: [
    { id: 'reporting-requirements-1', title: 'REGON (statistics) registration' },
    { id: 'reporting-requirements-2', title: 'ZUS inspections' },
    { id: 'reporting-requirements-3', title: 'Tax inspections' },
  ]},
  { id: 'how-to-start', title: 'How to become a freelancer - tips for beginners', children: [
    { id: 'how-to-start-1', title: 'How to define your profession and direction?' },
    { id: 'how-to-start-2', title: 'Who should start? Professions for beginners' },
    { id: 'how-to-start-3', title: 'Where to look - platforms and finding clients' },
    { id: 'how-to-start-4', title: 'Training - courses and resources' },
    { id: 'how-to-start-5', title: 'Course languages - availability' },
    { id: 'how-to-start-6', title: 'Practical tips for starting' },
  ]},
  { id: 'faq', title: 'FAQ - Questions and answers', children: [
    { id: 'faq-1', title: 'Basic registration questions' },
    { id: 'faq-2', title: 'Tax questions' },
    { id: 'faq-3', title: 'ZUS questions' },
    { id: 'faq-4', title: 'VAT questions' },
    { id: 'faq-5', title: 'Accounting questions' },
    { id: 'faq-6', title: 'International income questions' },
    { id: 'faq-7', title: 'Legalisation questions' },
    { id: 'faq-8', title: 'B2B and employment relationship questions' },
    { id: 'faq-9', title: 'Liability questions' },
  ]},
];

export const navigationSectionsDe: NavSection[] = [
  { id: 'introduction', title: 'Alles über Freelancing in Polen 2026', children: [
    { id: 'introduction-1', title: 'Warum Polen zum Hub für Freelancer wurde' },
    { id: 'introduction-2', title: 'Freelancing-Statistik in Polen' },
    { id: 'introduction-3', title: 'Gefragte Berufe und Durchschnittsgehälter' },
    { id: 'introduction-4', title: 'Plattformen für Freelancer' },
    { id: 'introduction-5', title: 'Durchschnittliche Stundensätze' },
  ]},
  { id: 'legal-status', title: 'Legal aufhalten und Freelancing in Polen', children: [
    { id: 'legal-status-1', title: 'PESEL und Aufenthaltsstatus 2026' },
    { id: 'legal-status-2', title: 'Recht auf Geschäftstätigkeit für Nicht-EU-Bürger' },
    { id: 'legal-status-3', title: 'Aufenthaltserlaubnis aus geschäftlichem Grund' },
    { id: 'legal-status-4', title: 'Blaue Karte EU für IT-Freelancer' },
    { id: 'legal-status-5', title: 'Arbeit mit Visum oder visumfrei' },
  ]},
  { id: 'unregistered-activity', title: 'Nicht angemeldete Tätigkeit', children: [
    { id: 'unregistered-activity-1', title: 'Was ist nicht angemeldete Tätigkeit?' },
    { id: 'unregistered-activity-2', title: 'Einkommensgrenze 2026' },
    { id: 'unregistered-activity-3', title: 'Wer hat Anspruch?' },
    { id: 'unregistered-activity-4', title: 'Pflichten – vereinfachtes Register' },
    { id: 'unregistered-activity-5', title: 'Versicherung (ZUS)' },
    { id: 'unregistered-activity-6', title: 'Steuererklärung (PIT-36)' },
  ]},
  { id: 'jdg', title: 'Jednoosobowa Działalność Gospodarcza (JDG)', children: [
    { id: 'jdg-1', title: 'Schritt-für-Schritt-Anmeldung über CEIDG' },
    { id: 'jdg-2', title: 'Tätigkeitscodes (PKD) wählen' },
    { id: 'jdg-3', title: 'Startdatum und Anmeldestelle' },
    { id: 'jdg-4', title: 'ZUS-Anmeldung – ZZA und ZUA' },
    { id: 'jdg-5', title: 'Bankkonto – privat oder geschäftlich?' },
    { id: 'jdg-6', title: 'Finanz- und Vermögenshaftung' },
  ]},
  { id: 'business-incubators', title: 'Freelancing über Business-Inkubatoren', children: [
    { id: 'business-incubators-1', title: 'Modell "Freelance as a Service"' },
    { id: 'business-incubators-2', title: 'Vorteile für Ausländer (mit Vorsicht)' },
    { id: 'business-incubators-3', title: 'Kosten – Abo vs. Steuer' },
    { id: 'business-incubators-4', title: 'Haftung in Inkubatoren' },
    { id: 'business-incubators-5', title: 'Aufenthaltserlaubnis und Legalisation' },
    { id: 'business-incubators-6', title: 'Grenzen des Modells' },
    { id: 'business-incubators-7', title: 'Vorteile ohne Sprach-/Buchhaltungskenntnisse' },
    { id: 'business-incubators-8', title: 'Kosten – Monatsabo vs. JDG-Steuer' },
    { id: 'business-incubators-9', title: 'Legalisation (Aufenthalt) über Inkubator' },
    { id: 'business-incubators-10', title: 'Tätigkeitsgrenzen in Inkubatoren' },
  ]},
  { id: 'civil-contracts', title: 'Zivilrechtliche Verträge (B2C)', children: [
    { id: 'civil-contracts-1', title: 'Umowa o dzieło: Für kreative Berufe' },
    { id: 'civil-contracts-2', title: 'Umowa zlecenie: Vergütung für Ablauf' },
    { id: 'civil-contracts-3', title: 'Brutto vs. Netto für Freelancer' },
    { id: 'civil-contracts-4', title: 'Besteuerung ausländischer Einkünfte' },
    { id: 'civil-contracts-5', title: 'Umowa zlecenie: Steuer und Sozialabgaben' },
    { id: 'civil-contracts-6', title: 'Brutto vs. Netto (Verträge)' },
    { id: 'civil-contracts-7', title: 'Besteuerung ausländischer Einkünfte (diese Verträge)' },
  ]},
  { id: 'laws-regulations', title: 'Recht und staatliche Regelung', children: [
    { id: 'laws-regulations-1', title: 'Unternehmergesetz (Ustawa o przedsiębiorcach)' },
    { id: 'laws-regulations-2', title: 'Abgabenordnung (Ordynacja podatkowa)' },
    { id: 'laws-regulations-3', title: 'Rechte bei Prüfungen (KAS)' },
    { id: 'laws-regulations-4', title: 'Datenschutz (DSGVO)' },
    { id: 'laws-regulations-5', title: 'Offizielle Hinweise zu Remote-Arbeit' },
  ]},
  { id: 'taxation-systems', title: 'Steuersysteme im Überblick', children: [
    { id: 'taxation-systems-1', title: 'Steuerskala (12% / 32%)' },
    { id: 'taxation-systems-2', title: 'Lineare Steuer (19%)' },
    { id: 'taxation-systems-3', title: 'Pauschalsteuer (ryczałt)' },
    { id: 'taxation-systems-4', title: 'Ryczałt: Stufen im Detail' },
    { id: 'taxation-systems-5', title: 'Beste Wahl 2026' },
  ]},
  { id: 'zus-insurance', title: 'Sozialversicherung und ZUS', children: [
    { id: 'zus-insurance-1', title: '"Ulga na start"-Erleichterung' },
    { id: 'zus-insurance-2', title: 'Mały ZUS Plus' },
    { id: 'zus-insurance-3', title: 'Regelbeiträge und "Chorobowe"' },
  ]},
  { id: 'vat', title: 'Umsatzsteuer (VAT) für Freelancer', children: [
    { id: 'vat-1', title: 'Grenze 200.000 PLN' },
    { id: 'vat-2', title: 'VAT-EU-Registrierung' },
  ]},
  { id: 'accounting-finance', title: 'Buchhaltung und Finanzen', children: [
    { id: 'accounting-finance-1', title: 'KPiR (Einnahmen-/Ausgabenbuch) führen' },
    { id: 'accounting-finance-2', title: 'KSeF-System 2026' },
    { id: 'accounting-finance-3', title: 'Steuerlich absetzbare Kosten' },
    { id: 'accounting-finance-4', title: 'Wo einen Buchhalter finden?' },
    { id: 'accounting-finance-5', title: 'E-Rechnung und KSeF 2026' },
    { id: 'accounting-finance-6', title: 'Absetzbare Kosten – Miete, Ausstattung, Fortbildung, Auto' },
    { id: 'accounting-finance-7', title: 'Professionelle Hilfe – Büro vs. Online' },
  ]},
  { id: 'technical-legal', title: 'Technische und rechtliche Aspekte', children: [
    { id: 'technical-legal-1', title: 'Profil Zaufany und mObywatel' },
    { id: 'technical-legal-2', title: 'Qualifizierte E-Signatur' },
    { id: 'technical-legal-3', title: 'Arbeit mit ausländischen Plattformen (Upwork, Fiverr)' },
  ]},
  { id: 'conclusions', title: 'Fazit – Strategie für erfolgreiches Freelancing', children: [
    { id: 'conclusions-1', title: 'Ihr Start-Checkliste' },
    { id: 'conclusions-2', title: 'Strategie für erfolgreiches Freelancing' },
  ]},
  { id: 'employment-vs-selfemployed', title: 'Selbstständig vs. Angestellt – was lohnt sich?', children: [
    { id: 'employment-vs-selfemployed-1', title: 'Urlaub und Krankheit' },
    { id: 'employment-vs-selfemployed-2', title: 'Stabilität' },
    { id: 'employment-vs-selfemployed-3', title: 'Nettoeinkommen' },
  ]},
  { id: 'legal-liability', title: 'Rechtliche Haftung des Freelancers', children: [
    { id: 'legal-liability-1', title: 'Haftung mit dem gesamten Vermögen' },
    { id: 'legal-liability-2', title: 'Berufshaftpflicht (OC)' },
  ]},
  { id: 'b2b-contracts', title: 'Besonderheiten B2B-Vertrag', children: [
    { id: 'b2b-contracts-1', title: 'Anzeichen Arbeitsverhältnis' },
    { id: 'b2b-contracts-2', title: 'Arbeit für früheren Arbeitgeber' },
  ]},
  { id: 'reporting-requirements', title: 'Meldepflichten und Prüfungen', children: [
    { id: 'reporting-requirements-1', title: 'REGON (Statistik)-Anmeldung' },
    { id: 'reporting-requirements-2', title: 'ZUS-Prüfungen' },
    { id: 'reporting-requirements-3', title: 'Steuerprüfungen' },
  ]},
  { id: 'how-to-start', title: 'Freelancer werden – Tipps für Einsteiger', children: [
    { id: 'how-to-start-1', title: 'Beruf und Richtung festlegen' },
    { id: 'how-to-start-2', title: 'Für wen lohnt sich der Einstieg?' },
    { id: 'how-to-start-3', title: 'Wo suchen – Plattformen und Kundenakquise' },
    { id: 'how-to-start-4', title: 'Weiterbildung – Kurse und Ressourcen' },
    { id: 'how-to-start-5', title: 'Sprachen der Kurse – Verfügbarkeit' },
    { id: 'how-to-start-6', title: 'Praktische Tipps für den Start' },
  ]},
  { id: 'faq', title: 'FAQ – Fragen und Antworten', children: [
    { id: 'faq-1', title: 'Grundfragen zur Anmeldung' },
    { id: 'faq-2', title: 'Steuerfragen' },
    { id: 'faq-3', title: 'ZUS-Fragen' },
    { id: 'faq-4', title: 'VAT-Fragen' },
    { id: 'faq-5', title: 'Buchhaltungsfragen' },
    { id: 'faq-6', title: 'Internationale Einkünfte' },
    { id: 'faq-7', title: 'Legalisation' },
    { id: 'faq-8', title: 'B2B und Arbeitsverhältnis' },
    { id: 'faq-9', title: 'Haftung' },
  ]},
];

/** Усі id (секції + підзаголовки) у порядку для визначення activeSection при скролі */
export function getAllNavIds(sections: NavSection[]): string[] {
  return sections.flatMap(s => [s.id, ...(s.children?.map(c => c.id) ?? [])]);
}
