export type NavItem = { id: string; title: string };
export type NavSection = { id: string; title: string; children?: NavItem[] };

export const navigationSectionsUk: NavSection[] = [
  { id: 'introduction', title: 'Все про фріланс в Польщі станом на 2026', children: [
    { id: 'introduction-1', title: 'Чому Польща стала хабом для українських фрілансерів?' },
    { id: 'introduction-2', title: 'Статистика фрілансу в Польщі' },
    { id: 'introduction-3', title: 'Найзатребуваніші професії та середні заробітні плати' },
    { id: 'introduction-4', title: 'Платформи для фрілансерів' },
    { id: 'introduction-5', title: 'Середні погодинні ставки' },
  ]},
  { id: 'legal-status', title: 'Легальне перебування і фріланс в Польщі', children: [
    { id: 'legal-status-1', title: 'Статус PESEL UKR та його актуальність у 2026 році' },
    { id: 'legal-status-2', title: 'Право на ведення господарської діяльності для громадян України' },
    { id: 'legal-status-3', title: 'Карта тимчасового побиту на підставі бізнесу' },
    { id: 'legal-status-4', title: 'Blue Card для висококваліфікованих IT-фрілансерів' },
    { id: 'legal-status-5', title: 'Можливість роботи за візою або в рамках безвізового руху' },
  ]},
  { id: 'unregistered-activity', title: 'Незареєстрована діяльність', children: [
    { id: 'unregistered-activity-1', title: 'Що таке незареєстрована діяльність?' },
    { id: 'unregistered-activity-2', title: 'Фінансовий ліміт доходу у 2026 році' },
    { id: 'unregistered-activity-3', title: 'Хто має право на цю форму' },
    { id: 'unregistered-activity-4', title: "Перелік обов'язків - спрощений реєстр" },
    { id: 'unregistered-activity-5', title: 'Питання страхування (ZUS)' },
    { id: 'unregistered-activity-6', title: 'Податкова звітність (PIT-36)' },
  ]},
  { id: 'jdg', title: 'Jednoosobowa Działalność Gospodarcza (JDG)', children: [
    { id: 'jdg-1', title: 'Покроковий алгоритм реєстрації через CEIDG' },
    { id: 'jdg-2', title: 'Вибір кодів діяльності (PKD)' },
    { id: 'jdg-3', title: 'Вибір дати початку та місце реєстрації' },
    { id: 'jdg-4', title: 'Реєстрація в ZUS - форми ZZA та ZUA' },
    { id: 'jdg-5', title: 'Банківський рахунок - приватний чи фірмовий' },
    { id: 'jdg-6', title: 'Фінансова та майнова відповідальність' },
  ]},
  { id: 'business-incubators', title: 'Фріланс чи навіть робота через Бізнес-інкубатори', children: [
    { id: 'business-incubators-1', title: 'Принцип роботи моделі "Freelance as a Service"' },
    { id: 'business-incubators-2', title: 'Переваги для іноземців (з обережністю)' },
    { id: 'business-incubators-3', title: 'Аналіз витрат - абонплата проти податків' },
    { id: 'business-incubators-4', title: 'Відповідальність у бізнес-інкубаторах' },
    { id: 'business-incubators-5', title: 'Питання легалізації та Карти побиту' },
    { id: 'business-incubators-6', title: 'Обмеження моделі' },
    { id: 'business-incubators-7', title: 'Переваги для іноземців без знання мови та бухгалтерії' },
    { id: 'business-incubators-8', title: 'Аналіз витрат - щомісячна абонплата проти податків JDG' },
    { id: 'business-incubators-9', title: 'Питання легалізації (карти побиту) через інкубатор' },
    { id: 'business-incubators-10', title: 'Обмеження у видах діяльності в рамках інкубатора' },
  ]},
  { id: 'civil-contracts', title: 'Цивільно-правові договори (B2C)', children: [
    { id: 'civil-contracts-1', title: 'Umowa o dzieło: Специфіка для творчих професій' },
    { id: 'civil-contracts-2', title: 'Umowa zlecenie: Оплата за процес' },
    { id: 'civil-contracts-3', title: 'Порівняння "брутто" та "нетто" для фрілансера' },
    { id: 'civil-contracts-4', title: 'Оподаткування доходів з-за кордону' },
    { id: 'civil-contracts-5', title: 'Umowa zlecenie: правила оподаткування та соціальні внески' },
    { id: 'civil-contracts-6', title: 'Порівняння "брутто" та "нетто" (договори)' },
    { id: 'civil-contracts-7', title: 'Оподаткування доходів з-за кордону через ці договори' },
  ]},
  { id: 'laws-regulations', title: 'Закони, норми та державне регулювання', children: [
    { id: 'laws-regulations-1', title: 'Закон про підприємців (Ustawa o przedsiębiorcach)' },
    { id: 'laws-regulations-2', title: 'Податковий кодекс (Ordynacja podatkowa)' },
    { id: 'laws-regulations-3', title: 'Права фрілансера під час перевірок (KAS)' },
    { id: 'laws-regulations-4', title: 'Захист персональних даних (RODO)' },
    { id: 'laws-regulations-5', title: "Офіційні роз'яснення щодо віддаленої роботи" },
  ]},
  { id: 'taxation-systems', title: 'Глибокий аналіз систем оподаткування', children: [
    { id: 'taxation-systems-1', title: 'Skala podatkowa (Загальна система 12% / 32%)' },
    { id: 'taxation-systems-2', title: 'Podatek liniowy (Лінійний податок 19%)' },
    { id: 'taxation-systems-3', title: 'Ryczałt (Ричалт, податок від обороту)' },
    { id: 'taxation-systems-4', title: 'Ryczałt: детальний розбір ставок' },
    { id: 'taxation-systems-5', title: 'Критерії вибору найвигіднішої системи у 2026 році' },
  ]},
  { id: 'zus-insurance', title: 'Соціальне страхування та ZUS', children: [
    { id: 'zus-insurance-1', title: 'Пільга "Ulga na start"' },
    { id: 'zus-insurance-2', title: 'Mały ZUS Plus' },
    { id: 'zus-insurance-3', title: 'Стандартні внески та "Chorobowe"' },
  ]},
  { id: 'vat', title: 'ПДВ (VAT) у житті фрілансера', children: [
    { id: 'vat-1', title: 'Ліміт 200 000 злотих' },
    { id: 'vat-2', title: 'Реєстрація VAT-UE' },
  ]},
  { id: 'accounting-finance', title: 'Бухгалтерія та фінансова гігієна', children: [
    { id: 'accounting-finance-1', title: 'Ведення KPiR (Книга доходів і витрат)' },
    { id: 'accounting-finance-2', title: 'Система KSeF у 2026 році' },
    { id: 'accounting-finance-3', title: 'Витрати, що зменшують податок' },
    { id: 'accounting-finance-4', title: 'Професійна допомога - де шукати бухгалтера' },
    { id: 'accounting-finance-5', title: 'Електронне фактурування та система KSeF у 2026 році' },
    { id: 'accounting-finance-6', title: 'Витрати, що зменшують податок - оренда, техніка, навчання, авто' },
    { id: 'accounting-finance-7', title: 'Професійна допомога - Biuro rachunkowe проти онлайн-сервісів' },
  ]},
  { id: 'technical-legal', title: 'Додаткові технічні та правові аспекти', children: [
    { id: 'technical-legal-1', title: 'Profil Zaufany та mObywatel' },
    { id: 'technical-legal-2', title: 'Електронний підпис (Podpis kwalifikowany)' },
    { id: 'technical-legal-3', title: 'Робота з іноземними платформами (Upwork, Fiverr)' },
  ]},
  { id: 'conclusions', title: 'Висновки - стратегія успішного фрілансу', children: [
    { id: 'conclusions-1', title: 'Ваш чек-лист на старт' },
    { id: 'conclusions-2', title: 'Стратегія успішного фрілансу' },
  ]},
  { id: 'employment-vs-selfemployed', title: 'Самозайнятість vs Umowa o pracę', children: [
    { id: 'employment-vs-selfemployed-1', title: 'Відпустки та лікарняні' },
    { id: 'employment-vs-selfemployed-2', title: 'Стабільність' },
    { id: 'employment-vs-selfemployed-3', title: 'Гроші на руки' },
  ]},
  { id: 'legal-liability', title: 'Юридична відповідальність фрілансера', children: [
    { id: 'legal-liability-1', title: 'Відповідальність усім майном' },
    { id: 'legal-liability-2', title: 'Страхування професійної відповідальності (OC)' },
  ]},
  { id: 'b2b-contracts', title: 'Специфіка B2B-контракту', children: [
    { id: 'b2b-contracts-1', title: 'Ознаки трудових відносин' },
    { id: 'b2b-contracts-2', title: 'Працювати на колишнього роботодавця' },
  ]},
  { id: 'reporting-requirements', title: 'Вимоги до звітності та перевірки', children: [
    { id: 'reporting-requirements-1', title: 'Реєстрація в статистиці (REGON)' },
    { id: 'reporting-requirements-2', title: 'Перевірки ZUS' },
    { id: 'reporting-requirements-3', title: 'Перевірки податкової' },
  ]},
  { id: 'how-to-start', title: 'Як стати фрілансером - поради для початківців', children: [
    { id: 'how-to-start-1', title: 'Як визначити свою професію та напрямок' },
    { id: 'how-to-start-2', title: 'На кого варто починати - професії для новачків' },
    { id: 'how-to-start-3', title: 'Куди йти - платформи та способи пошуку клієнтів' },
    { id: 'how-to-start-4', title: 'Навчання - курси та ресурси' },
    { id: 'how-to-start-5', title: 'Мови навчання - таблиця доступності курсів' },
    { id: 'how-to-start-6', title: 'Практичні поради для старту' },
  ]},
  { id: 'faq', title: 'FAQ - Запитання та відповіді', children: [
    { id: 'faq-1', title: 'Основні питання про реєстрацію' },
    { id: 'faq-2', title: 'Питання про оподаткування' },
    { id: 'faq-3', title: 'Питання про ZUS' },
    { id: 'faq-4', title: 'Питання про VAT' },
    { id: 'faq-5', title: 'Питання про бухгалтерію' },
    { id: 'faq-6', title: 'Питання про міжнародні доходи' },
    { id: 'faq-7', title: 'Питання про легалізацію' },
    { id: 'faq-8', title: 'Питання про B2B-контракти та трудові відносини' },
    { id: 'faq-9', title: 'Питання про відповідальність' },
  ]},
];

export const navigationSectionsPl: NavSection[] = [
  { id: 'introduction', title: 'Wszystko o freelancingu w Polsce na 2026', children: [
    { id: 'introduction-1', title: 'Dlaczego Polska stała się hubem dla ukraińskich freelancerów?' },
    { id: 'introduction-2', title: 'Statystyki freelancingu w Polsce' },
    { id: 'introduction-3', title: 'Najbardziej poszukiwane zawody i średnie zarobki' },
    { id: 'introduction-4', title: 'Platformy dla freelancerów' },
    { id: 'introduction-5', title: 'Średnie stawki godzinowe' },
  ]},
  { id: 'legal-status', title: 'Legalny pobyt i freelancing w Polsce', children: [
    { id: 'legal-status-1', title: 'Status PESEL UKR i jego aktualność w 2026' },
    { id: 'legal-status-2', title: 'Prawo do prowadzenia działalności dla obywateli Ukrainy' },
    { id: 'legal-status-3', title: 'Karta czasowego pobytu na podstawie biznesu' },
    { id: 'legal-status-4', title: 'Blue Card dla wysoko wykwalifikowanych IT-freelancerów' },
    { id: 'legal-status-5', title: 'Możliwość pracy na wizę lub w ruchu bezwizowym' },
  ]},
  { id: 'unregistered-activity', title: 'Działalność nierejestrowana', children: [
    { id: 'unregistered-activity-1', title: 'Czym jest działalność nierejestrowana?' },
    { id: 'unregistered-activity-2', title: 'Limit finansowy dochodu w 2026' },
    { id: 'unregistered-activity-3', title: 'Kto ma prawo do tej formy' },
    { id: 'unregistered-activity-4', title: 'Wykaz obowiązków - uproszczony rejestr' },
    { id: 'unregistered-activity-5', title: 'Kwestie ubezpieczeń (ZUS)' },
    { id: 'unregistered-activity-6', title: 'Sprawozdawczość podatkowa (PIT-36)' },
  ]},
  { id: 'jdg', title: 'Jednoosobowa Działalność Gospodarcza (JDG)', children: [
    { id: 'jdg-1', title: 'Algorytm rejestracji przez CEIDG krok po kroku' },
    { id: 'jdg-2', title: 'Wybór kodów działalności (PKD)' },
    { id: 'jdg-3', title: 'Wybór daty rozpoczęcia i miejsce rejestracji' },
    { id: 'jdg-4', title: 'Rejestracja w ZUS - formularze ZZA i ZUA' },
    { id: 'jdg-5', title: 'Konto bankowe - prywatne czy firmowe' },
    { id: 'jdg-6', title: 'Odpowiedzialność finansowa i majątkowa' },
  ]},
  { id: 'business-incubators', title: 'Freelancing lub nawet praca przez Inkubatory biznesowe', children: [
    { id: 'business-incubators-1', title: 'Zasada modelu "Freelance as a Service"' },
    { id: 'business-incubators-2', title: 'Korzyści dla cudzoziemców (z ostrożnością)' },
    { id: 'business-incubators-3', title: 'Analiza kosztów - abonament vs podatki' },
    { id: 'business-incubators-4', title: 'Odpowiedzialność w inkubatorach' },
    { id: 'business-incubators-5', title: 'Kwestie legalizacji i Karty pobytu' },
    { id: 'business-incubators-6', title: 'Ograniczenia modelu' },
    { id: 'business-incubators-7', title: 'Korzyści dla cudzoziemców bez znajomości języka i księgowości' },
    { id: 'business-incubators-8', title: 'Analiza kosztów - abonament miesięczny vs podatki JDG' },
    { id: 'business-incubators-9', title: 'Kwestie legalizacji (karty pobytu) przez inkubator' },
    { id: 'business-incubators-10', title: 'Ograniczenia rodzajów działalności w inkubatorze' },
  ]},
  { id: 'civil-contracts', title: 'Umowy cywilnoprawne (B2C)', children: [
    { id: 'civil-contracts-1', title: 'Umowa o dzieło: Specyfika dla zawodów kreatywnych' },
    { id: 'civil-contracts-2', title: 'Umowa zlecenie: Płatność za proces' },
    { id: 'civil-contracts-3', title: 'Porównanie "brutto" i "netto" dla freelancera' },
    { id: 'civil-contracts-4', title: 'Opodatkowanie dochodów z zagranicy' },
    { id: 'civil-contracts-5', title: 'Umowa zlecenie: zasady opodatkowania i składki społeczne' },
    { id: 'civil-contracts-6', title: 'Porównanie "brutto" i "netto" (umowy)' },
    { id: 'civil-contracts-7', title: 'Opodatkowanie dochodów z zagranicy przez te umowy' },
  ]},
  { id: 'laws-regulations', title: 'Prawa, normy i regulacje państwowe', children: [
    { id: 'laws-regulations-1', title: 'Ustawa o przedsiębiorcach' },
    { id: 'laws-regulations-2', title: 'Ordynacja podatkowa' },
    { id: 'laws-regulations-3', title: 'Prawa freelancera podczas kontroli (KAS)' },
    { id: 'laws-regulations-4', title: 'Ochrona danych osobowych (RODO)' },
    { id: 'laws-regulations-5', title: 'Oficjalne wyjaśnienia dotyczące pracy zdalnej' },
  ]},
  { id: 'taxation-systems', title: 'Szczegółowa analiza systemów podatkowych', children: [
    { id: 'taxation-systems-1', title: 'Skala podatkowa (12% / 32%)' },
    { id: 'taxation-systems-2', title: 'Podatek liniowy (19%)' },
    { id: 'taxation-systems-3', title: 'Ryczałt (podatek od obrotu)' },
    { id: 'taxation-systems-4', title: 'Ryczałt: szczegółowe stawki' },
    { id: 'taxation-systems-5', title: 'Kryteria wyboru najkorzystniejszego systemu w 2026' },
  ]},
  { id: 'zus-insurance', title: 'Ubezpieczenia społeczne i ZUS', children: [
    { id: 'zus-insurance-1', title: 'Ulga na start' },
    { id: 'zus-insurance-2', title: 'Mały ZUS Plus' },
    { id: 'zus-insurance-3', title: 'Standardowe składki i "Chorobowe"' },
  ]},
  { id: 'vat', title: 'VAT w życiu freelancera', children: [
    { id: 'vat-1', title: 'Limit 200 000 zł' },
    { id: 'vat-2', title: 'Rejestracja VAT-UE' },
  ]},
  { id: 'accounting-finance', title: 'Księgowość i higiena finansowa', children: [
    { id: 'accounting-finance-1', title: 'Prowadzenie KPiR' },
    { id: 'accounting-finance-2', title: 'System KSeF w 2026' },
    { id: 'accounting-finance-3', title: 'Koszty obniżające podatek' },
    { id: 'accounting-finance-4', title: 'Pomoc profesjonalna - gdzie szukać księgowego' },
    { id: 'accounting-finance-5', title: 'Fakturowanie elektroniczne i KSeF w 2026' },
    { id: 'accounting-finance-6', title: 'Koszty obniżające podatek - wynajem, sprzęt, szkolenia, auto' },
    { id: 'accounting-finance-7', title: 'Pomoc profesjonalna - Biuro rachunkowe vs serwisy online' },
  ]},
  { id: 'technical-legal', title: 'Dodatkowe aspekty techniczne i prawne', children: [
    { id: 'technical-legal-1', title: 'Profil Zaufany i mObywatel' },
    { id: 'technical-legal-2', title: 'Podpis kwalifikowany' },
    { id: 'technical-legal-3', title: 'Praca z zagranicznymi platformami (Upwork, Fiverr)' },
  ]},
  { id: 'conclusions', title: 'Wnioski - strategia udanego freelancingu', children: [
    { id: 'conclusions-1', title: 'Twój checklist na start' },
    { id: 'conclusions-2', title: 'Strategia udanego freelancingu' },
  ]},
  { id: 'employment-vs-selfemployed', title: 'Samozatrudnienie vs Umowa o pracę', children: [
    { id: 'employment-vs-selfemployed-1', title: 'Urlopy i zwolnienia lekarskie' },
    { id: 'employment-vs-selfemployed-2', title: 'Stabilność' },
    { id: 'employment-vs-selfemployed-3', title: 'Pieniądze do ręki' },
  ]},
  { id: 'legal-liability', title: 'Odpowiedzialność prawna freelancera', children: [
    { id: 'legal-liability-1', title: 'Odpowiedzialność całym majątkiem' },
    { id: 'legal-liability-2', title: 'Ubezpieczenie OC zawodowe' },
  ]},
  { id: 'b2b-contracts', title: 'Specyfika umowy B2B', children: [
    { id: 'b2b-contracts-1', title: 'Znamiona stosunku pracy' },
    { id: 'b2b-contracts-2', title: 'Praca u byłego pracodawcy' },
  ]},
  { id: 'reporting-requirements', title: 'Wymagania dotyczące sprawozdawczości i kontroli', children: [
    { id: 'reporting-requirements-1', title: 'Rejestracja w statystyce (REGON)' },
    { id: 'reporting-requirements-2', title: 'Kontrole ZUS' },
    { id: 'reporting-requirements-3', title: 'Kontrole podatkowe' },
  ]},
  { id: 'how-to-start', title: 'Jak zostać freelancerem - porady dla początkujących', children: [
    { id: 'how-to-start-1', title: 'Jak określić swój zawód i kierunek' },
    { id: 'how-to-start-2', title: 'Dla kogo warto zaczynać - zawody dla początkujących' },
    { id: 'how-to-start-3', title: 'Gdzie szukać - platformy i sposoby znajdowania klientów' },
    { id: 'how-to-start-4', title: 'Szkolenia - kursy i zasoby' },
    { id: 'how-to-start-5', title: 'Języki szkoleń - dostępność kursów' },
    { id: 'how-to-start-6', title: 'Praktyczne porady na start' },
  ]},
  { id: 'faq', title: 'FAQ - Pytania i odpowiedzi', children: [
    { id: 'faq-1', title: 'Podstawowe pytania o rejestrację' },
    { id: 'faq-2', title: 'Pytania o opodatkowanie' },
    { id: 'faq-3', title: 'Pytania o ZUS' },
    { id: 'faq-4', title: 'Pytania o VAT' },
    { id: 'faq-5', title: 'Pytania o księgowość' },
    { id: 'faq-6', title: 'Pytania o dochody międzynarodowe' },
    { id: 'faq-7', title: 'Pytania o legalizację' },
    { id: 'faq-8', title: 'Pytania o umowy B2B i stosunek pracy' },
    { id: 'faq-9', title: 'Pytania o odpowiedzialność' },
  ]},
];

/** Усі id (секції + підзаголовки) у порядку для визначення activeSection при скролі */
export function getAllNavIds(sections: NavSection[]): string[] {
  return sections.flatMap(s => [s.id, ...(s.children?.map(c => c.id) ?? [])]);
}
